---
name: 'Create file'
description: 'Get secrets from vault and expose as environment variables'
inputs:
  create_secret_file:
    description: 'Create a file with secrets'
    required: false
outputs:
  secrets_file:
    description: 'File with secrets'
    value: ${{ steps.create_secrets.outputs.secrets_file }}
  
runs:
  using: "composite"
  steps:
    - name: "Install YQ"
      shell: bash
      id: install-yq
      run: pip install --no-cache-dir --upgrade yq
    - name: 'Create Secrets File'
      id: create_secrets
      shell: bash
      run: |
        SECRETS_FILE="${{ inputs.create_secret_file }}"
        echo "File content" > $SECRETS_FILE
        echo "secrets_file=$(pwd)/$SECRETS_FILE" >> $GITHUB_OUTPUT